import 'package:flutter/material.dart';

class HomeFeedScreen extends StatelessWidget {
  const HomeFeedScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('InstaAI', style: TextStyle(fontFamily: 'Roboto', fontWeight: FontWeight.bold, fontSize: 24)),
        actions: [
          IconButton(
            icon: const Icon(Icons.favorite_border),
            onPressed: () {},
          ),
          IconButton(
            icon: const Icon(Icons.send),
            onPressed: () {},
          ),
        ],
      ),
      body: ListView.builder(
        itemCount: 10,
        itemBuilder: (context, index) {
          return const PostWidget();
        },
      ),
    );
  }
}

class PostWidget extends StatelessWidget {
  const PostWidget({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        ListTile(
          leading: const CircleAvatar(
            backgroundColor: Colors.grey,
            child: Icon(Icons.person, color: Colors.white),
          ),
          title: const Text('user_name', style: TextStyle(fontWeight: FontWeight.bold)),
          subtitle: const Text('Location'),
          trailing: const Icon(Icons.more_vert),
        ),
        Container(
          height: 300,
          color: Colors.grey.shade300,
          child: const Center(child: Icon(Icons.image, size: 50, color: Colors.grey)),
        ),
        Padding(
          padding: const EdgeInsets.all(8.0),
          child: Row(
            children: [
              const Icon(Icons.favorite_border),
              const SizedBox(width: 16),
              const Icon(Icons.comment_outlined),
              const SizedBox(width: 16),
              const Icon(Icons.send),
              const Spacer(),
              const Icon(Icons.bookmark_border),
            ],
          ),
        ),
        const Padding(
          padding: EdgeInsets.symmetric(horizontal: 16.0),
          child: Text('1,234 likes', style: TextStyle(fontWeight: FontWeight.bold)),
        ),
        const Padding(
          padding: EdgeInsets.symmetric(horizontal: 16.0, vertical: 4.0),
          child: Text.rich(
            TextSpan(
              children: [
                TextSpan(text: 'user_name ', style: TextStyle(fontWeight: FontWeight.bold)),
                TextSpan(text: 'This is a great photo generated by my AI agent! #ai #generated'),
              ],
            ),
          ),
        ),
        const Padding(
          padding: EdgeInsets.symmetric(horizontal: 16.0),
          child: Text('View all 45 comments', style: TextStyle(color: Colors.grey)),
        ),
        const SizedBox(height: 16),
      ],
    );
  }
}
